### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by ghost** [leon332157/json-store-client#5]
When I try to run this simple code :

```python
import json
import json_store_client
import os

# Read JSON file
with open('data.json') as f:
    data = json.load(f)

# Store it to JSON STORE
client = json_store_client.Client(os.environ['JSON_STORE_SECRET'])  
client.store("data", data)
```

I receive following error :

> Traceback (most recent call last):
  File ".\store_json.py", line 2, in <module>
    import json_store_client
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\json_store_client\__init__.py", line 77
    'User-Agent': f'Mozilla/5.0 Python/json-store-client/{self.version}'
                                                                       ^
> SyntaxError: invalid syntax

**Comment by ghost** [comment]
My bad, I tried this code on Google colab and it worked like a charm. 

My local python installation must be messed up...
